protocols:
  netconf:
    port: 830
    rpc_timeout: 10 
  gnmi:
    port: 9339
    skip_verify: true 
modules:
  grafana:
    port: 8080
  enricher:
    folder: "/var/metadata"
    interval: 720
    workers: 2
    port: 10000
  portal:
    https: true 
    server_crt: "server.crt"
    server_key: "server.key"
    port: 8081
